### ISSUE TITLE
bug in your blog descripton

### ISSUE THREAD

**Issue by yasdfgr** [oneguyoneblog/tally-light-esp32-for-blackmagic-atem-switcher#1]
As you #include <ATEM.h>, we need to adjust the includes in the files ../ATEM/Atem.h and ../ATEM/Atem.cpp and not in ../ATEMbase/.

**Comment by OneGuy-OneBlog** [comment]
> As you #include <ATEM.h>, we need to adjust the includes in the files ../ATEM/Atem.h and ../ATEM/Atem.cpp and not in ../ATEMbase/.

Hi yasdfgr! Actually, the description is correct, but I accidentally published an old version of the sketch. I have published the correct one now. Thank you for noticing the mistake!
